# Generated by Django 5.1.15 on 2026-03-17 01:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbershop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(help_text='Se usa para el link público de reservas.')),
                ('booking_uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID público para el link de reservas.', unique=True)),
                ('address', models.TextField(blank=True, verbose_name='dirección')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 7 y 15 dígitos, opcionalmente con + al inicio.', regex='^\\+?\\d{7,15}$')], verbose_name='teléfono')),
                ('timezone', models.CharField(default='America/Bogota', help_text='Zona horaria de la sucursal.', max_length=50)),
                ('open_hour', models.PositiveSmallIntegerField(default=8, verbose_name='hora de apertura')),
                ('close_hour', models.PositiveSmallIntegerField(default=20, verbose_name='hora de cierre')),
                ('closed_days', models.JSONField(blank=True, default=list, help_text='Lista de días de la semana cerrados (0=lunes, 6=domingo). Ej: [6]', verbose_name='días cerrados')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'barbería',
                'verbose_name_plural': 'barberías',
                'db_table': 'accounts_barbershop',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 7 y 15 dígitos, opcionalmente con + al inicio.', regex='^\\+?\\d{7,15}$')], verbose_name='teléfono')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('barber', 'Barbero')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barbershop', models.ForeignKey(blank=True, help_text='Null = acceso a todas las sucursales de la organización.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.barbershop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membresía',
                'verbose_name_plural': 'membresías',
                'db_table': 'accounts_membership',
            },
        ),
        migrations.CreateModel(
            name='BarberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='nombre artístico')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 7 y 15 dígitos, opcionalmente con + al inicio.', regex='^\\+?\\d{7,15}$')], verbose_name='teléfono')),
                ('bio', models.TextField(blank=True, verbose_name='biografía')),
                ('photo', models.ImageField(blank=True, upload_to='barber_photos/')),
                ('instagram', models.URLField(blank=True)),
                ('buffer_minutes', models.PositiveSmallIntegerField(default=0, help_text='Minutos de buffer entre citas.', verbose_name='descanso entre servicios (min)')),
                ('lunch_start', models.TimeField(blank=True, help_text='Dejar vacío si no tiene horario fijo de almuerzo.', null=True, verbose_name='inicio almuerzo')),
                ('lunch_end', models.TimeField(blank=True, null=True, verbose_name='fin almuerzo')),
                ('is_active', models.BooleanField(default=True)),
                ('membership', models.OneToOneField(limit_choices_to={'role': 'barber'}, on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to='accounts.membership')),
            ],
            options={
                'verbose_name': 'perfil de barbero',
                'verbose_name_plural': 'perfiles de barbero',
                'db_table': 'accounts_barber_profile',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(help_text='Identificador URL-friendly.', unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='org_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organización',
                'verbose_name_plural': 'organizaciones',
                'db_table': 'accounts_organization',
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbershops', to='accounts.organization'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'organization', 'barbershop'), name='unique_membership'),
        ),
        migrations.AlterUniqueTogether(
            name='barbershop',
            unique_together={('organization', 'slug')},
        ),
    ]
