# Generated by Django 5.1.15 on 2026-03-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='sucursales',
            field=models.ManyToManyField(blank=True, help_text='Sucursales donde trabaja este barbero.', related_name='barberos', to='accounts.barbershop', verbose_name='sucursales asignadas'),
        ),
    ]
