# Generated by Django 5.1.15 on 2026-05-02 20:25

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_barbero_sucursales_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='sucursales',
            field=models.ManyToManyField(blank=True, help_text='Sucursales adicionales asignadas (para selección múltiple).', related_name='memberships_assigned', to='accounts.barbershop'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('barber', 'Barbero'), ('staff', 'Personal Barberia')], max_length=10),
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('barber', 'Barbero'), ('staff', 'Personal Barberia')], max_length=10)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.accounts.models.get_default_expiration)),
                ('is_used', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.organization')),
                ('sucursales', models.ManyToManyField(blank=True, related_name='invitations', to='accounts.barbershop')),
            ],
            options={
                'verbose_name': 'invitación a organización',
                'verbose_name_plural': 'invitaciones a organización',
                'db_table': 'accounts_organization_invitation',
            },
        ),
    ]
