# Generated by Django 5.1.15 on 2026-05-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_membership_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country_code',
            field=models.CharField(default='CO', help_text='Código ISO del país. Determina la pasarela de pago por defecto.', max_length=2, verbose_name='país (ISO 3166-1 alpha-2)'),
        ),
    ]
