# Generated by Django 5.1.15 on 2026-06-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='intervalo_apertura_dias',
            field=models.PositiveSmallIntegerField(default=15, help_text='Días máximo en el futuro en los que un cliente puede agendar. Por defecto 15.', verbose_name='ventana de apertura (días)'),
        ),
    ]
