# Generated by Django 5.2.7 on 2026-06-03 01:20

from django.db import migrations, models


def initialize_country_code_for_existing_users(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.exclude(phone="").update(country_code="57")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_intervalo_apertura_dias"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country_code",
            field=models.CharField(
                default="57",
                help_text="Código de país para el número telefónico (ej. 57 para Colombia).",
                max_length=5,
                verbose_name="código de país",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification",
            field=models.BooleanField(default=False, verbose_name="correo verificado"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verification",
            field=models.BooleanField(
                default=False, verbose_name="teléfono verificado"
            ),
        ),
        migrations.RunPython(
            initialize_country_code_for_existing_users, migrations.RunPython.noop
        ),
    ]
