# Generated by Django 5.1.15 on 2026-06-06 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_country_code_user_email_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='maps_instructions',
            field=models.TextField(blank=True, help_text='Indicaciones opcionales para llegar a la sucursal.', verbose_name='indicaciones de llegada'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='maps_location',
            field=models.CharField(blank=True, db_index=True, help_text="Coordenadas del mapa en formato 'lat,lng'.", max_length=100, verbose_name='ubicación (lat,lng)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No iniciado'), (1, 'Paso 1 – Organización y Sucursal'), (2, 'Paso 2 – Catálogo de Servicios'), (3, 'Completado')], db_index=True, default=0, verbose_name='paso de onboarding'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(help_text='Código de país para el número telefónico (ej. 57 para Colombia).', max_length=5, verbose_name='código de país'),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('is_consumed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'token de verificación de correo',
                'verbose_name_plural': 'tokens de verificación de correo',
                'db_table': 'accounts_email_verification_token',
                'ordering': ['-created_at'],
            },
        ),
    ]
