# Generated by Django 5.1.15 on 2026-06-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_barbershop_maps_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='hora_apertura',
            field=models.TimeField(blank=True, help_text='Hora exacta de apertura de la sucursal.', null=True, verbose_name='hora de apertura (TimeField)'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='hora_cierre',
            field=models.TimeField(blank=True, help_text='Hora exacta de cierre de la sucursal.', null=True, verbose_name='hora de cierre (TimeField)'),
        ),
    ]
