# Generated by Django 5.1.15 on 2026-06-08 19:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_barbershop_hora_apertura_barbershop_hora_cierre'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLinkVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='correo a verificar')),
                ('otp_hash', models.CharField(max_length=64, verbose_name='hash del OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('expires_at', models.DateTimeField(verbose_name='expira en')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='intentos')),
                ('cooldown_until', models.DateTimeField(blank=True, null=True, verbose_name='cooldown hasta')),
            ],
            options={
                'verbose_name': 'verificación de enlace de correo',
                'verbose_name_plural': 'verificaciones de enlace de correo',
                'db_table': 'accounts_email_link_verification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='teléfono')),
                ('country_code', models.CharField(default='', max_length=5, verbose_name='código de país')),
                ('otp_hash', models.CharField(max_length=64, verbose_name='hash del OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado')),
                ('expires_at', models.DateTimeField(verbose_name='expira en')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='intentos')),
                ('cooldown_until', models.DateTimeField(blank=True, null=True, verbose_name='cooldown hasta')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('register', 'Registro'), ('email_link', 'Enlazar correo')], default='login', max_length=10, verbose_name='propósito')),
            ],
            options={
                'verbose_name': 'solicitud de verificación SMS',
                'verbose_name_plural': 'solicitudes de verificación SMS',
                'db_table': 'accounts_sms_verification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, default='', help_text="Código de país para el número telefónico (ej. 57 para Colombia). Sin el símbolo '+'.", max_length=5, verbose_name='código de país'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 7 y 15 dígitos, opcionalmente con + al inicio.', regex='^\\+?\\d{7,15}$')], verbose_name='teléfono'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('country_code', 'phone'), name='unique_phone_per_country'),
        ),
        migrations.AddField(
            model_name='emaillinkverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_link_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
