# Generated by Django 5.1.15 on 2026-06-11 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_sms_verification_and_email_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillinkverification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_link_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
