# Generated by Django 5.1.15 on 2026-05-18 00:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_membership_sucursales_alter_membership_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(default=list)),
                ('max_barbers', models.PositiveIntegerField(blank=True, null=True)),
                ('max_branches', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_plan',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['is_active'], name='billing_pla_is_acti_0aba70_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('interval', models.CharField(choices=[('month', 'Mensual'), ('year', 'Anual')], max_length=10)),
                ('provider', models.CharField(max_length=20)),
                ('provider_price_id', models.CharField(max_length=100)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_plan_price',
                'ordering': ['-is_current', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=80)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Fallido')], default='received', max_length=15)),
                ('raw_payload', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'billing_webhook_event',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', 'event_id'], name='billing_web_provide_507488_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_provider_event')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=100)),
                ('provider_customer_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('trialing', 'En prueba'), ('active', 'Activa'), ('past_due', 'Pago pendiente'), ('canceled', 'Cancelada'), ('expired', 'Expirada')], default='trialing', max_length=15)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('plan_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.planprice')),
            ],
            options={
                'db_table': 'billing_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('provider', models.CharField(max_length=20)),
                ('provider_invoice_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('paid', 'Pagada'), ('pending', 'Pendiente'), ('failed', 'Fallida')], default='pending', max_length=15)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_webhook_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.organization')),
                ('plan_price_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.planprice')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.subscription')),
            ],
            options={
                'db_table': 'billing_invoice',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.AddIndex(
            model_name='planprice',
            index=models.Index(fields=['plan', 'is_current'], name='billing_pla_plan_id_e6fb78_idx'),
        ),
        migrations.AddIndex(
            model_name='planprice',
            index=models.Index(fields=['provider', 'provider_price_id'], name='billing_pla_provide_599cd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('plan', 'provider', 'currency', 'interval'), name='unique_active_price_per_plan_provider'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['provider_subscription_id'], name='billing_sub_provide_fcdcca_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['provider_customer_id'], name='billing_sub_provide_cc2755_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['trialing', 'active', 'past_due'])), fields=('organization',), name='one_active_subscription_per_org'),
        ),
    ]
