# Generated by Django 5.1.15 on 2026-05-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_user_subscription_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('wompi', 'Wompi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='planprice',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('wompi', 'Wompi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='processedwebhookevent',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('wompi', 'Wompi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('wompi', 'Wompi')], max_length=20),
        ),
    ]
