# Generated by Django 5.1.15 on 2026-03-17 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        ('inventory', '__first__'),
        ('scheduling', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_type', models.CharField(choices=[('service', 'Servicio'), ('product', 'Venta de producto'), ('mixed', 'Mixta')], max_length=10, verbose_name='tipo')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('completed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha cierre')),
                ('appointment', models.OneToOneField(blank=True, help_text='Vinculada a una cita completada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='scheduling.appointment')),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='accounts.barberprofile')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.barbershop')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='clients.client')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'db_table': 'finance_sale',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('service', 'Servicio'), ('product', 'Producto')], max_length=10, verbose_name='tipo')),
                ('description', models.CharField(max_length=200, verbose_name='descripción')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.sale')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.service')),
            ],
            options={
                'verbose_name': 'ítem de venta',
                'verbose_name_plural': 'ítems de venta',
                'db_table': 'finance_sale_item',
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['barbershop', 'completed_at'], name='finance_sal_barbers_018b98_idx'),
        ),
    ]
