# Generated by Django 5.1.15 on 2026-04-14 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio venta')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de cambio')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.product')),
            ],
            options={
                'verbose_name': 'historial de precio de producto',
                'verbose_name_plural': 'historial de precios de producto',
                'db_table': 'inventory_historial_precio_producto',
                'ordering': ['-changed_at'],
            },
        ),
    ]
