# Generated by Django 5.1.15 on 2026-04-24 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_barbero_sucursales_m2m'),
        ('inventory', '0002_historial_precio_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('restock', 'Reabastecimiento'), ('transfer', 'Transferencia'), ('adjustment', 'Ajuste')], max_length=15, verbose_name='tipo de movimiento')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('barbershop_destiny', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements_destiny', to='accounts.barbershop', verbose_name='sucursal destino')),
                ('barbershop_origin', models.ForeignKey(blank=True, help_text='Null para Reabastecimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements_origin', to='accounts.barbershop', verbose_name='sucursal origen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'db_table': 'inventory_movement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Unidades sumadas.', verbose_name='cantidad')),
                ('stock_previous', models.IntegerField(help_text='Stock antes del movimiento.', verbose_name='stock previo')),
                ('stock_resulting', models.IntegerField(help_text='Stock después del movimiento.', verbose_name='stock resultante')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorymovement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_items', to='inventory.product')),
            ],
            options={
                'verbose_name': 'ítem de movimiento',
                'verbose_name_plural': 'ítems de movimiento',
                'db_table': 'inventory_movement_item',
            },
        ),
    ]
