# Generated by Django 5.1.15 on 2026-05-01 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0004_inventorymovement_created_by_product_created_by_and_more'),
    ]

    operations = [
        # 1. Add organization field allowing null
        migrations.AddField(
            model_name='productcategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization'),
        ),
        # 2. Backfill organization from existing barbershop relations
        migrations.RunSQL(
            sql="""
            UPDATE inventory_category c
            SET organization_id = b.organization_id
            FROM accounts_barbershop b
            WHERE c.barbershop_id = b.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 3. Fallback for any rows without barbershop (assign to organization_id=1, assuming 1 exists)
        migrations.RunSQL(
            sql="UPDATE inventory_category SET organization_id = 1 WHERE organization_id IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 4. Alter organization field to NOT NULL
        migrations.AlterField(
            model_name='productcategory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization'),
        ),
        # 5. Alter barbershop field to allow null
        migrations.AlterField(
            model_name='productcategory',
            name='barbershop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='accounts.barbershop'),
        ),
        # 6. Add is_active field
        migrations.AddField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activa'),
        ),
    ]
