# Generated by Django 5.1.15 on 2026-05-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_productcategory_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('restock', 'Reabastecimiento'), ('sale', 'Venta'), ('adjustment', 'Ajuste'), ('loss', 'Pérdida'), ('return', 'Devolución'), ('transfer', 'Transferencia')], max_length=15, verbose_name='motivo'),
        ),
    ]
