# Generated by Django 5.1.15 on 2026-03-17 01:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='inicio programado')),
                ('end_time', models.DateTimeField(help_text='Calculado automáticamente según la duración de los servicios + buffer.', verbose_name='fin estimado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No asistió')], db_index=True, default='pending', max_length=15, verbose_name='estado')),
                ('payment_method', models.CharField(choices=[('in_store', 'Pago en el local')], default='in_store', max_length=15, verbose_name='método de pago')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('cancelled_reason', models.TextField(blank=True, verbose_name='motivo cancelación')),
                ('reminder_24h_sent', models.BooleanField(default=False)),
                ('reminder_1h_sent', models.BooleanField(default=False)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.barberprofile')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.barbershop')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'db_table': 'scheduling_appointment',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exception_type', models.CharField(choices=[('vacation', 'Vacaciones'), ('sick_leave', 'Permiso médico'), ('personal', 'Permiso personal'), ('lunch', 'Almuerzo'), ('break', 'Descanso'), ('other', 'Otro')], max_length=20, verbose_name='tipo')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('start', models.DateTimeField(verbose_name='inicio')),
                ('end', models.DateTimeField(verbose_name='fin')),
                ('is_recurring', models.BooleanField(default=False, help_text='Si es True, se repite semanalmente (ej: almuerzo diario).', verbose_name='recurrente')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='accounts.barberprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'excepción de horario',
                'verbose_name_plural': 'excepciones de horario',
                'db_table': 'scheduling_exception',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duración estimada en minutos.', validators=[django.core.validators.MinValueValidator(5)], verbose_name='duración (min)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('is_active', models.BooleanField(default=True)),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.barbershop')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'db_table': 'scheduling_service',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BarberService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Si se deja vacío, se usa el precio del servicio.', max_digits=10, null=True, verbose_name='precio personalizado')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='accounts.barberprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='scheduling.service')),
            ],
            options={
                'verbose_name': 'servicio de barbero',
                'verbose_name_plural': 'servicios de barbero',
                'db_table': 'scheduling_barber_service',
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_charged', models.DecimalField(decimal_places=2, help_text='Snapshot del precio al momento de la reserva.', max_digits=10, verbose_name='precio cobrado')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='scheduling.appointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scheduling.service')),
            ],
            options={
                'verbose_name': 'servicio de cita',
                'verbose_name_plural': 'servicios de cita',
                'db_table': 'scheduling_appointment_service',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField(verbose_name='hora inicio')),
                ('end_time', models.TimeField(verbose_name='hora fin')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='accounts.barberprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'horario laboral',
                'verbose_name_plural': 'horarios laborales',
                'db_table': 'scheduling_work_schedule',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['barber', 'start_time'], name='scheduling__barber__605b53_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'start_time'], name='scheduling__status_c22d78_idx'),
        ),
        migrations.AddConstraint(
            model_name='barberservice',
            constraint=models.UniqueConstraint(fields=('barber', 'service'), name='unique_barber_service'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.UniqueConstraint(fields=('barber', 'day_of_week'), name='unique_barber_day'),
        ),
    ]
