# Generated by Django 5.1.15 on 2026-03-18 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        ('inventory', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=15, verbose_name='estado')),
                ('fecha', models.DateTimeField(db_index=True, verbose_name='fecha de intervención')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='fin de intervención')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('appointment', models.OneToOneField(blank=True, help_text='Cita de origen, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervencion', to='scheduling.appointment')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='accounts.barberprofile')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.barbershop')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='clients.client')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'intervención',
                'verbose_name_plural': 'intervenciones',
                'db_table': 'scheduling_intervencion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='IntervencionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento de uso.', max_digits=10, verbose_name='precio unitario')),
                ('intervencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_usados', to='scheduling.intervencion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uso_intervenciones', to='inventory.product')),
            ],
            options={
                'verbose_name': 'producto de intervención',
                'verbose_name_plural': 'productos de intervención',
                'db_table': 'scheduling_intervencion_producto',
            },
        ),
        migrations.CreateModel(
            name='IntervencionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_cobrado', models.DecimalField(decimal_places=2, help_text='Snapshot del precio al momento de la intervención.', max_digits=10, verbose_name='precio cobrado')),
                ('intervencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='scheduling.intervencion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scheduling.service')),
            ],
            options={
                'verbose_name': 'servicio de intervención',
                'verbose_name_plural': 'servicios de intervención',
                'db_table': 'scheduling_intervencion_servicio',
            },
        ),
        migrations.AddIndex(
            model_name='intervencion',
            index=models.Index(fields=['barber', 'fecha'], name='scheduling__barber__22b532_idx'),
        ),
        migrations.AddIndex(
            model_name='intervencion',
            index=models.Index(fields=['estado', 'fecha'], name='scheduling__estado_4fac55_idx'),
        ),
    ]
