# Generated by Django 5.1.15 on 2026-04-07 23:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('scheduling', '0003_add_categoria_servicio_and_historial_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad consumida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_asociados', to='inventory.product')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_consumidos', to='scheduling.service')),
            ],
            options={
                'verbose_name': 'producto de servicio',
                'verbose_name_plural': 'productos de servicio',
                'db_table': 'scheduling_servicio_producto',
                'constraints': [models.UniqueConstraint(fields=('servicio', 'producto'), name='unique_servicio_producto')],
            },
        ),
    ]
