# Generated by Django 5.1.15 on 2026-04-15 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_servicioproducto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barberservice',
            options={'verbose_name': 'configuración servicio barbero', 'verbose_name_plural': 'configuraciones servicio barbero'},
        ),
        migrations.AddField(
            model_name='barberservice',
            name='custom_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Si se deja vacío, se usa la duración del servicio.', null=True, verbose_name='duración personalizada (min)'),
        ),
        migrations.CreateModel(
            name='HistorialCambiosConfiguracionBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(help_text='precio_personalizado o duracion_personalizada', max_length=50, verbose_name='campo modificado')),
                ('valor_anterior', models.CharField(blank=True, max_length=50, verbose_name='valor anterior')),
                ('valor_nuevo', models.CharField(blank=True, max_length=50, verbose_name='valor nuevo')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo / nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='scheduling.barberservice')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial config. barbero',
                'verbose_name_plural': 'historial config. barbero',
                'db_table': 'scheduling_historial_config_barbero',
                'ordering': ['-created_at'],
            },
        ),
    ]
