# Generated by Django 5.1.15 on 2026-04-19 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_config_servicio_barbero_custom_duration_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='incluye_producto_en_precio',
            field=models.BooleanField(default=False, help_text='Snapshot del estado del servicio al momento de la reserva.', verbose_name='producto incluido en precio'),
        ),
        migrations.AddField(
            model_name='historialprecioservicio',
            name='incluye_producto_en_precio',
            field=models.BooleanField(default=False, verbose_name='producto incluido en precio'),
        ),
        migrations.AddField(
            model_name='intervencionproducto',
            name='intervencion_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_en_servicio', to='scheduling.intervencionservicio', verbose_name='servicio de intervención asociado'),
        ),
        migrations.AddField(
            model_name='intervencionservicio',
            name='incluye_producto_en_precio',
            field=models.BooleanField(default=False, help_text='Snapshot del estado del servicio al momento de la intervención.', verbose_name='producto incluido en precio'),
        ),
        migrations.AddField(
            model_name='service',
            name='incluye_producto_en_precio',
            field=models.BooleanField(default=False, help_text='Si está activo, el costo del producto asociado se considera dentro del precio del servicio.', verbose_name='producto incluido en precio'),
        ),
    ]
