# Generated by Django 5.1.15 on 2026-04-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_add_incluye_producto_en_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialprecioservicio',
            name='incluye_producto_en_precio',
        ),
        migrations.RemoveField(
            model_name='service',
            name='incluye_producto_en_precio',
        ),
        migrations.AddField(
            model_name='intervencionproducto',
            name='incluido_en_precio',
            field=models.BooleanField(default=False, help_text='Snapshot del estado al momento de la intervención.', verbose_name='incluido en precio del servicio'),
        ),
        migrations.AddField(
            model_name='servicioproducto',
            name='incluido_en_precio',
            field=models.BooleanField(default=False, help_text='Si está activo, el costo de este producto se considera dentro del precio del servicio.', verbose_name='incluido en precio del servicio'),
        ),
    ]
