# Generated by Django 5.1.15 on 2026-04-19 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_move_incluye_to_servicio_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentservice',
            name='incluye_producto_en_precio',
        ),
        migrations.RemoveField(
            model_name='intervencionservicio',
            name='incluye_producto_en_precio',
        ),
    ]
