# Generated by Django 5.1.15 on 2026-05-28 19:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_country_code'),
        ('inventory', '0006_alter_stockmovement_reason'),
        ('scheduling', '0009_appointment_created_by_barberservice_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intervencionproducto',
            name='monto_barberia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto correspondiente a la barbería (congelado al completar).', max_digits=12, null=True, verbose_name='monto barbería'),
        ),
        migrations.AddField(
            model_name='intervencionproducto',
            name='monto_barbero',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto correspondiente al barbero (congelado al completar).', max_digits=12, null=True, verbose_name='monto barbero'),
        ),
        migrations.AddField(
            model_name='intervencionproducto',
            name='porcentaje_comision_aplicado',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Snapshot del porcentaje de comisión del barbero al momento de completar.', null=True, verbose_name='porcentaje comisión aplicado'),
        ),
        migrations.AddField(
            model_name='intervencionservicio',
            name='monto_barberia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto correspondiente a la barbería (congelado al completar).', max_digits=12, null=True, verbose_name='monto barbería'),
        ),
        migrations.AddField(
            model_name='intervencionservicio',
            name='monto_barbero',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto correspondiente al barbero (congelado al completar).', max_digits=12, null=True, verbose_name='monto barbero'),
        ),
        migrations.AddField(
            model_name='intervencionservicio',
            name='porcentaje_comision_aplicado',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Snapshot del porcentaje de comisión del barbero al momento de completar.', null=True, verbose_name='porcentaje comisión aplicado'),
        ),
        migrations.CreateModel(
            name='ComisionProductoBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('porcentaje', models.PositiveSmallIntegerField(default=0, help_text='Porcentaje de comisión del barbero (0-100). Por defecto 0%.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='porcentaje')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_productos', to='accounts.barberprofile')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.barbershop')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_barberos', to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'comisión producto barbero',
                'verbose_name_plural': 'comisiones producto barbero',
                'db_table': 'scheduling_comison_producto_barbero',
                'constraints': [models.UniqueConstraint(fields=('barber', 'producto'), name='unique_comision_producto_barbero')],
            },
        ),
        migrations.CreateModel(
            name='ComisionServicioBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('porcentaje', models.PositiveSmallIntegerField(default=50, help_text='Porcentaje de comisión del barbero (0-100). Por defecto 50%.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='porcentaje')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_servicios', to='accounts.barberprofile')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.barbershop')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_barberos', to='scheduling.service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'comisión servicio barbero',
                'verbose_name_plural': 'comisiones servicio barbero',
                'db_table': 'scheduling_comision_servicio_barbero',
                'constraints': [models.UniqueConstraint(fields=('barber', 'servicio'), name='unique_comision_servicio_barbero')],
            },
        ),
        migrations.CreateModel(
            name='HistorialComisionesBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('servicio', 'Servicio'), ('producto', 'Producto')], max_length=10, verbose_name='tipo')),
                ('item_id', models.PositiveIntegerField(help_text='ID del servicio o producto modificado.', verbose_name='ID del item')),
                ('item_nombre', models.CharField(blank=True, help_text='Nombre del servicio o producto al momento del cambio.', max_length=200, verbose_name='nombre del item')),
                ('valor_anterior', models.PositiveSmallIntegerField(help_text='Porcentaje de comisión anterior.', verbose_name='valor anterior (%)')),
                ('valor_nuevo', models.PositiveSmallIntegerField(help_text='Porcentaje de comisión nuevo.', verbose_name='valor nuevo (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_comisiones', to='accounts.barberprofile')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial comisión barbero',
                'verbose_name_plural': 'historial comisiones barbero',
                'db_table': 'scheduling_historial_comisiones_barbero',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['barber', 'tipo', 'item_id'], name='scheduling__barber__b04ef3_idx')],
            },
        ),
    ]
