# Generated by Django 5.2.7 on 2026-06-03 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_user_client_unique_client_user_per_org'),
        ('scheduling', '0010_comisiones_barbero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones', to='clients.client'),
        ),
    ]
