# Generated by Django 5.1.15 on 2026-03-17 01:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 7 y 15 dígitos.', regex='^\\+?\\d{7,15}$')], verbose_name='teléfono')),
                ('notes', models.TextField(blank=True, verbose_name='notas internas')),
                ('source', models.CharField(default='booking', help_text='Cómo llegó: booking, manual, import, etc.', max_length=30, verbose_name='origen')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='Vinculado si el cliente se autenticó con Google.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'clients_client',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('organization', 'email'), name='unique_client_email_per_org')],
            },
        ),
    ]
