# Generated by Django 5.1.15 on 2026-04-15 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_barbero_sucursales_m2m'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('historia_clinica', models.TextField(blank=True, help_text='Historial médico/estético relevante del cliente.', verbose_name='historia clínica')),
                ('recomendaciones', models.TextField(blank=True, help_text='Recomendaciones de cuidado o tratamiento.', verbose_name='recomendaciones')),
                ('notas_medicas', models.TextField(blank=True, help_text='Notas adicionales de carácter médico o estético.', verbose_name='notas médicas/estéticas')),
                ('datos_extra', models.JSONField(blank=True, default=dict, help_text='Campos flexibles en formato JSON.', verbose_name='datos adicionales')),
            ],
            options={
                'verbose_name': 'ficha clínica',
                'verbose_name_plural': 'fichas clínicas',
                'db_table': 'clients_ficha_clinica',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_client_email_per_org',
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('email__gt', ''), ('is_active', True)), fields=('organization', 'email'), name='unique_client_email_per_org'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__gt', ''), ('is_active', True)), fields=('organization', 'phone'), name='unique_client_phone_per_org'),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_clinicas', to='clients.client'),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
