# Generated by Django 5.1.15 on 2026-05-27 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_country_code'),
        ('clients', '0003_client_created_by_fichaclinica_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Vinculado si el cliente se autenticó con Google.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False), ('is_active', True)), fields=('organization', 'user'), name='unique_client_user_per_org'),
        ),
    ]
