# Generated by Django 5.1.15 on 2026-03-17 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('channel', models.CharField(choices=[('email', 'Correo electrónico')], max_length=10)),
                ('notif_type', models.CharField(choices=[('reminder_24h', 'Recordatorio 24h'), ('reminder_1h', 'Recordatorio 1h'), ('barber_reminder', 'Recordatorio barbero'), ('cancellation', 'Cancelación'), ('confirmation', 'Confirmación')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scheduling.appointment')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'db_table': 'notifications_log',
                'ordering': ['-sent_at'],
            },
        ),
    ]
