# Generated by Django 5.1.15 on 2026-05-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='teléfono destinatario'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('email', 'Correo electrónico'), ('sms', 'SMS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notif_type',
            field=models.CharField(choices=[('reminder_24h', 'Recordatorio 24h'), ('reminder_1h', 'Recordatorio 1h'), ('barber_reminder', 'Recordatorio barbero'), ('cancellation', 'Cancelación'), ('confirmation', 'Confirmación'), ('reschedule_client', 'Reprogramación (cliente)'), ('reschedule_barber', 'Reprogramación (barbero)')], max_length=25),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
