# Generated by Django 5.2.7 on 2026-06-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_sms_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notif_type',
            field=models.CharField(choices=[('reminder_24h', 'Recordatorio 24h'), ('reminder_1h', 'Recordatorio 1h'), ('barber_reminder', 'Recordatorio barbero'), ('cancellation', 'Cancelación'), ('confirmation', 'Confirmación'), ('reschedule_client', 'Reprogramación (cliente)'), ('reschedule_barber', 'Reprogramación (barbero)'), ('phone_otp', 'OTP de teléfono'), ('email_verification', 'Verificación de correo')], max_length=25),
        ),
    ]
